# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'point2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for point2
  pod 'SwiftyDropbox'
  pod 'Projection'

  target 'point2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
